import { GitHubRepository } from '../../../shared/types';

export class MockTrendingService {
    /**
     * 获取模拟的周度热门项目
     */
    getWeeklyTrending(): GitHubRepository[] {
        return [
            {
                id: 1,
                name: 'react',
                full_name: 'facebook/react',
                description: 'A declarative, efficient, and flexible JavaScript library for building user interfaces.',
                html_url: 'https://github.com/facebook/react',
                language: 'JavaScript',
                stargazers_count: 220000,
                forks_count: 45000,
                topics: ['javascript', 'react', 'ui', 'frontend'],
                created_at: '2013-05-24T16:15:54Z',
                updated_at: '2025-09-22T17:30:00Z',
                pushed_at: '2025-09-22T17:30:00Z',
                size: 100000,
                default_branch: 'main',
                open_issues_count: 1000,
                watchers_count: 220000,
                archived: false,
                disabled: false,
                private: false,
                fork: false,
                license: {
                    key: 'mit',
                    name: 'MIT License',
                    spdx_id: 'MIT',
                    url: 'https://api.github.com/licenses/mit',
                },
            },
            {
                id: 2,
                name: 'vue',
                full_name: 'vuejs/vue',
                description: 'Vue.js is a progressive, incrementally-adoptable JavaScript framework for building UI on the web.',
                html_url: 'https://github.com/vuejs/vue',
                language: 'JavaScript',
                stargazers_count: 200000,
                forks_count: 35000,
                topics: ['javascript', 'vue', 'framework', 'frontend'],
                created_at: '2013-07-29T03:24:51Z',
                updated_at: '2025-09-22T16:45:00Z',
                pushed_at: '2025-09-22T16:45:00Z',
                size: 80000,
                default_branch: 'main',
                open_issues_count: 500,
                watchers_count: 200000,
                archived: false,
                disabled: false,
                private: false,
                fork: false,
                license: {
                    key: 'mit',
                    name: 'MIT License',
                    spdx_id: 'MIT',
                    url: 'https://api.github.com/licenses/mit',
                },
            },
            {
                id: 3,
                name: 'angular',
                full_name: 'angular/angular',
                description: 'The modern web developer\'s platform',
                html_url: 'https://github.com/angular/angular',
                language: 'TypeScript',
                stargazers_count: 90000,
                forks_count: 25000,
                topics: ['typescript', 'angular', 'framework', 'frontend'],
                created_at: '2014-09-18T16:12:01Z',
                updated_at: '2025-09-22T15:20:00Z',
                pushed_at: '2025-09-22T15:20:00Z',
                size: 120000,
                default_branch: 'main',
                open_issues_count: 800,
                watchers_count: 90000,
                archived: false,
                disabled: false,
                private: false,
                fork: false,
                license: {
                    key: 'mit',
                    name: 'MIT License',
                    spdx_id: 'MIT',
                    url: 'https://api.github.com/licenses/mit',
                },
            },
        ];
    }

    /**
     * 获取模拟的月度热门项目
     */
    getMonthlyTrending(): GitHubRepository[] {
        return [
            {
                id: 4,
                name: 'next.js',
                full_name: 'vercel/next.js',
                description: 'The React Framework for Production',
                html_url: 'https://github.com/vercel/next.js',
                language: 'JavaScript',
                stargazers_count: 120000,
                forks_count: 28000,
                topics: ['javascript', 'react', 'nextjs', 'framework'],
                created_at: '2016-10-25T23:24:51Z',
                updated_at: '2025-09-22T14:30:00Z',
                pushed_at: '2025-09-22T14:30:00Z',
                size: 150000,
                default_branch: 'canary',
                open_issues_count: 600,
                watchers_count: 120000,
                archived: false,
                disabled: false,
                private: false,
                fork: false,
                license: {
                    key: 'mit',
                    name: 'MIT License',
                    spdx_id: 'MIT',
                    url: 'https://api.github.com/licenses/mit',
                },
            },
            {
                id: 5,
                name: 'nuxt',
                full_name: 'nuxt/nuxt',
                description: 'The Intuitive Vue Framework',
                html_url: 'https://github.com/nuxt/nuxt',
                language: 'JavaScript',
                stargazers_count: 50000,
                forks_count: 12000,
                topics: ['javascript', 'vue', 'nuxt', 'framework'],
                created_at: '2016-10-26T00:00:00Z',
                updated_at: '2025-09-22T13:15:00Z',
                pushed_at: '2025-09-22T13:15:00Z',
                size: 80000,
                default_branch: 'main',
                open_issues_count: 300,
                watchers_count: 50000,
                archived: false,
                disabled: false,
                private: false,
                fork: false,
                license: {
                    key: 'mit',
                    name: 'MIT License',
                    spdx_id: 'MIT',
                    url: 'https://api.github.com/licenses/mit',
                },
            },
        ];
    }

    /**
     * 获取模拟的季度热门项目
     */
    getQuarterlyTrending(): GitHubRepository[] {
        return [
            {
                id: 6,
                name: 'svelte',
                full_name: 'sveltejs/svelte',
                description: 'Cybernetically enhanced web apps',
                html_url: 'https://github.com/sveltejs/svelte',
                language: 'JavaScript',
                stargazers_count: 80000,
                forks_count: 15000,
                topics: ['javascript', 'svelte', 'framework', 'compiler'],
                created_at: '2016-11-20T21:30:00Z',
                updated_at: '2025-09-22T12:00:00Z',
                pushed_at: '2025-09-22T12:00:00Z',
                size: 60000,
                default_branch: 'main',
                open_issues_count: 400,
                watchers_count: 80000,
                archived: false,
                disabled: false,
                private: false,
                fork: false,
                license: {
                    key: 'mit',
                    name: 'MIT License',
                    spdx_id: 'MIT',
                    url: 'https://api.github.com/licenses/mit',
                },
            },
            {
                id: 7,
                name: 'solid',
                full_name: 'solidjs/solid',
                description: 'A declarative, efficient, and flexible JavaScript library for building user interfaces.',
                html_url: 'https://github.com/solidjs/solid',
                language: 'TypeScript',
                stargazers_count: 30000,
                forks_count: 8000,
                topics: ['typescript', 'solid', 'framework', 'reactive'],
                created_at: '2018-04-20T00:00:00Z',
                updated_at: '2025-09-22T10:45:00Z',
                pushed_at: '2025-09-22T10:45:00Z',
                size: 40000,
                default_branch: 'main',
                open_issues_count: 200,
                watchers_count: 30000,
                archived: false,
                disabled: false,
                private: false,
                fork: false,
                license: {
                    key: 'mit',
                    name: 'MIT License',
                    spdx_id: 'MIT',
                    url: 'https://api.github.com/licenses/mit',
                },
            },
        ];
    }

    /**
     * 获取模拟的总榜数据
     */
    getOverallRanking(): GitHubRepository[] {
        return [
            {
                id: 1,
                name: 'react',
                full_name: 'facebook/react',
                description: 'A declarative, efficient, and flexible JavaScript library for building user interfaces.',
                html_url: 'https://github.com/facebook/react',
                language: 'JavaScript',
                stargazers_count: 220000,
                forks_count: 45000,
                topics: ['javascript', 'react', 'ui', 'frontend'],
                created_at: '2013-05-24T16:15:54Z',
                updated_at: '2025-09-22T17:30:00Z',
                pushed_at: '2025-09-22T17:30:00Z',
                size: 100000,
                default_branch: 'main',
                open_issues_count: 1000,
                watchers_count: 220000,
                archived: false,
                disabled: false,
                private: false,
                fork: false,
                license: {
                    key: 'mit',
                    name: 'MIT License',
                    spdx_id: 'MIT',
                    url: 'https://api.github.com/licenses/mit',
                },
            },
            {
                id: 2,
                name: 'vue',
                full_name: 'vuejs/vue',
                description: 'Vue.js is a progressive, incrementally-adoptable JavaScript framework for building UI on the web.',
                html_url: 'https://github.com/vuejs/vue',
                language: 'JavaScript',
                stargazers_count: 200000,
                forks_count: 35000,
                topics: ['javascript', 'vue', 'framework', 'frontend'],
                created_at: '2013-07-29T03:24:51Z',
                updated_at: '2025-09-22T16:45:00Z',
                pushed_at: '2025-09-22T16:45:00Z',
                size: 80000,
                default_branch: 'main',
                open_issues_count: 500,
                watchers_count: 200000,
                archived: false,
                disabled: false,
                private: false,
                fork: false,
                license: {
                    key: 'mit',
                    name: 'MIT License',
                    spdx_id: 'MIT',
                    url: 'https://api.github.com/licenses/mit',
                },
            },
            {
                id: 3,
                name: 'angular',
                full_name: 'angular/angular',
                description: 'The modern web developer\'s platform',
                html_url: 'https://github.com/angular/angular',
                language: 'TypeScript',
                stargazers_count: 90000,
                forks_count: 25000,
                topics: ['typescript', 'angular', 'framework', 'frontend'],
                created_at: '2014-09-18T16:12:01Z',
                updated_at: '2025-09-22T15:20:00Z',
                pushed_at: '2025-09-22T15:20:00Z',
                size: 120000,
                default_branch: 'main',
                open_issues_count: 800,
                watchers_count: 90000,
                archived: false,
                disabled: false,
                private: false,
                fork: false,
                license: {
                    key: 'mit',
                    name: 'MIT License',
                    spdx_id: 'MIT',
                    url: 'https://api.github.com/licenses/mit',
                },
            },
            {
                id: 4,
                name: 'next.js',
                full_name: 'vercel/next.js',
                description: 'The React Framework for Production',
                html_url: 'https://github.com/vercel/next.js',
                language: 'JavaScript',
                stargazers_count: 120000,
                forks_count: 28000,
                topics: ['javascript', 'react', 'nextjs', 'framework'],
                created_at: '2016-10-25T23:24:51Z',
                updated_at: '2025-09-22T14:30:00Z',
                pushed_at: '2025-09-22T14:30:00Z',
                size: 150000,
                default_branch: 'canary',
                open_issues_count: 600,
                watchers_count: 120000,
                archived: false,
                disabled: false,
                private: false,
                fork: false,
                license: {
                    key: 'mit',
                    name: 'MIT License',
                    spdx_id: 'MIT',
                    url: 'https://api.github.com/licenses/mit',
                },
            },
            {
                id: 5,
                name: 'nuxt',
                full_name: 'nuxt/nuxt',
                description: 'The Intuitive Vue Framework',
                html_url: 'https://github.com/nuxt/nuxt',
                language: 'JavaScript',
                stargazers_count: 50000,
                forks_count: 12000,
                topics: ['javascript', 'vue', 'nuxt', 'framework'],
                created_at: '2016-10-26T00:00:00Z',
                updated_at: '2025-09-22T13:15:00Z',
                pushed_at: '2025-09-22T13:15:00Z',
                size: 80000,
                default_branch: 'main',
                open_issues_count: 300,
                watchers_count: 50000,
                archived: false,
                disabled: false,
                private: false,
                fork: false,
                license: {
                    key: 'mit',
                    name: 'MIT License',
                    spdx_id: 'MIT',
                    url: 'https://api.github.com/licenses/mit',
                },
            },
        ];
    }
}
